import 'dart:io';
import 'package:astro_tale/util/images.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:open_filex/open_filex.dart';

class TarotPdfService {
  static Future<void> generateAndOpenPdf({
    required String userName,
    required String spread,
    required List<Map<String, String>> cards,
  }) async {
    try {
      final pdf = pw.Document();

      /// Load logo image
      final logoBytes = (await rootBundle.load(
        'assets/images/astrologo.png',
      )).buffer.asUint8List();
      final logoImage = pw.MemoryImage(logoBytes);

      final headerStyle = pw.TextStyle(
        fontSize: 24,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.indigo500,
      );

      final tableHeaderStyle = pw.TextStyle(
        fontSize: 13,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.white,
      );

      final bodyStyle = const pw.TextStyle(fontSize: 12);

      pdf.addPage(
        pw.MultiPage(
          margin: const pw.EdgeInsets.all(32),
          footer: (context) => pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              "Page ${context.pageNumber} of ${context.pagesCount}",
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
            ),
          ),
          build: (context) => [
            /// 🔷 Header with Logo
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Image(logoImage, height: 70),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text("Tarot Reading Report", style: headerStyle),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      DateFormat("dd MMM yyyy, hh:mm a").format(DateTime.now()),
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ],
                ),
              ],
            ),

            pw.SizedBox(height: 25),

            /// 👤 User Info Table
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              columnWidths: const {
                0: pw.FlexColumnWidth(2),
                1: pw.FlexColumnWidth(5),
              },
              children: [
                _infoRow("Client Name", userName),
                _infoRow("Spread Type", spread),
              ],
            ),

            pw.SizedBox(height: 25),

            pw.Text(
              "Tarot Cards Interpretation",
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.indigo,
              ),
            ),

            pw.SizedBox(height: 12),

            /// 🃏 Tarot Cards Table
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              columnWidths: const {
                0: pw.FlexColumnWidth(1.2),
                1: pw.FlexColumnWidth(2.5),
                2: pw.FlexColumnWidth(5),
              },
              children: [
                /// Header Row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.indigo),
                  children: [
                    _tableCell("Card", tableHeaderStyle),
                    _tableCell("Title", tableHeaderStyle),
                    _tableCell("Meaning", tableHeaderStyle),
                  ],
                ),

                /// Data Rows
                ...cards.asMap().entries.map((entry) {
                  final index = entry.key + 1;
                  final card = entry.value;

                  return pw.TableRow(
                    children: [
                      _tableCell(index.toString(), bodyStyle),
                      _tableCell(card["title"] ?? "", bodyStyle),
                      _tableCell(card["description"] ?? "", bodyStyle),
                    ],
                  );
                }),
              ],
            ),

            pw.SizedBox(height: 25),
            pw.Divider(),

            pw.Center(
              child: pw.Text(
                "Generated by Astronexus Astrology • For personal guidance only",
                style: pw.TextStyle(
                  fontSize: 10,
                  fontStyle: pw.FontStyle.italic,
                  color: PdfColors.grey600,
                ),
              ),
            ),
          ],
        ),
      );

      /// Save file
      final dir = await getApplicationDocumentsDirectory();
      final fileName =
          "astronexus_tarot_${DateTime.now().millisecondsSinceEpoch}.pdf";
      final file = File("${dir.path}/$fileName");

      await file.writeAsBytes(await pdf.save());

      /// Open file
      await OpenFilex.open(file.path);
    } catch (e) {
      print("PDF Generation Error: $e");
    }
  }

  /// Info table row
  static pw.TableRow _infoRow(String title, String value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(
            title,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
        ),
        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(value)),
      ],
    );
  }

  /// Table cell
  static pw.Widget _tableCell(String text, pw.TextStyle style) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(text, style: style),
    );
  }
}
