import 'dart:io';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';

class BirthChartPdfService {
  static Future<void> generateAndDownloadPdf({
    required String rashi,
    required String nakshatra,
    required String ascSign,
    required double ascLongitude,
    required Map<String, dynamic> houses,
  }) async {
    final pdf = pw.Document();

    final titleStyle = pw.TextStyle(
      fontSize: 26,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.deepOrange,
    );

    final labelStyle = pw.TextStyle(
      fontSize: 16,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.blueGrey900,
    );

    final valueStyle = pw.TextStyle(fontSize: 16, color: PdfColors.black);

    final houseLabelStyle = pw.TextStyle(
      fontSize: 14,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.orange,
    );

    final houseValueStyle = pw.TextStyle(fontSize: 14, color: PdfColors.black);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Center(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text("Birth Chart", style: titleStyle),
                pw.SizedBox(height: 20),

                // Main Info
                pw.RichText(
                  text: pw.TextSpan(
                    children: [
                      pw.TextSpan(text: "Rashi: ", style: labelStyle),
                      pw.TextSpan(text: rashi, style: valueStyle),
                    ],
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.RichText(
                  text: pw.TextSpan(
                    children: [
                      pw.TextSpan(text: "Nakshatra: ", style: labelStyle),
                      pw.TextSpan(text: nakshatra, style: valueStyle),
                    ],
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.RichText(
                  text: pw.TextSpan(
                    children: [
                      pw.TextSpan(text: "Ascendant: ", style: labelStyle),
                      pw.TextSpan(
                        text: "$ascSign (${ascLongitude.toStringAsFixed(2)}°)",
                        style: valueStyle,
                      ),
                    ],
                  ),
                ),
                pw.SizedBox(height: 20),
                pw.Divider(),

                // Houses
                ...houses.entries.map((e) {
                  final house = e.key;
                  final data = e.value;
                  final planets = (data['planets'] as List).join(', ');

                  return pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 6),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          "House $house: ${data['sign']}",
                          style: houseLabelStyle,
                        ),
                        pw.Text("Planets: $planets", style: houseValueStyle),
                        pw.Divider(),
                      ],
                    ),
                  );
                }).toList(),

                pw.SizedBox(height: 20),
                pw.Text(
                  "Generated by Astrology App",
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                ),
              ],
            ),
          );
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File("${dir.path}/birth_chart.pdf");

    await file.writeAsBytes(await pdf.save());

    /// ✅ OPEN FILE DIRECTLY
    await OpenFilex.open(file.path);
  }
}
