import 'dart:io';
import 'dart:typed_data';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:open_filex/open_filex.dart';

class BirthChartPdfService {
  static Future<void> generateAndDownloadPdf({
    required String chartImageUrl,
    required String rashi,
    required String nakshatra,
    required String ascSign,
    required double ascLongitude,
  }) async {
    try {
      final response = await http.get(Uri.parse(chartImageUrl));
      if (response.statusCode != 200) {
        throw Exception("Failed to load chart image");
      }

      final Uint8List imageBytes = response.bodyBytes;
      final bool isSvg = chartImageUrl.toLowerCase().endsWith(".svg");

      final pdf = pw.Document();

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(24),
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                /// 🟣 TITLE
                pw.Text(
                  "Birth Chart Report",
                  style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),

                pw.SizedBox(height: 6),

                pw.Text(
                  "Vedic Astrology Kundali",
                  style: const pw.TextStyle(
                    fontSize: 14,
                    color: PdfColors.grey700,
                  ),
                ),

                pw.Divider(thickness: 1.5),
                pw.SizedBox(height: 20),

                /// 🟣 LARGE CENTERED CHART
                pw.Container(
                  height: 420,
                  width: double.infinity,
                  alignment: pw.Alignment.center,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey400),
                    borderRadius: pw.BorderRadius.circular(12),
                  ),
                  padding: const pw.EdgeInsets.all(12),
                  child: isSvg
                      ? pw.SvgImage(svg: String.fromCharCodes(imageBytes))
                      : pw.Image(
                          pw.MemoryImage(imageBytes),
                          fit: pw.BoxFit.contain,
                        ),
                ),

                pw.SizedBox(height: 30),

                /// 🟣 DETAILS SECTION
                pw.Container(
                  width: double.infinity,
                  padding: const pw.EdgeInsets.all(16),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: pw.BorderRadius.circular(12),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        "Birth Details",
                        style: pw.TextStyle(
                          fontSize: 18,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),

                      pw.SizedBox(height: 12),

                      _infoRow("Rashi", rashi),
                      _infoRow("Nakshatra", nakshatra),
                      _infoRow("Ascendant Sign", ascSign),
                      _infoRow(
                        "Ascendant Degree",
                        "${ascLongitude.toStringAsFixed(2)}°",
                      ),
                    ],
                  ),
                ),

                pw.Spacer(),

                /// 🟣 FOOTER
                pw.Divider(),
                pw.Text(
                  "Generated by AstroNexus | Vedic Birth Chart ",
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            );
          },
        ),
      );

      final dir = await getApplicationDocumentsDirectory();
      final file = File("${dir.path}/birth_chart_report.pdf");
      await file.writeAsBytes(await pdf.save());

      await OpenFilex.open(file.path);
    } catch (e) {
      print("PDF Error: $e");
    }
  }

  static pw.Widget _infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 13),
          ),
          pw.Text(value, style: const pw.TextStyle(fontSize: 13)),
        ],
      ),
    );
  }
}
