import "dart:io";

import "package:astro_tale/services/api_services/chatbot/chat_bot_services.dart";
import "package:open_filex/open_filex.dart";
import "package:path_provider/path_provider.dart";
import "package:pdf/pdf.dart";
import "package:pdf/widgets.dart" as pw;

class MatiReportPdfService {
  const MatiReportPdfService._();

  static Future<File> generatePdf(MatiChatResponse response) async {
    final report = response.report;
    if (report == null || !report.hasContent) {
      throw Exception("Report data is not available for PDF export.");
    }

    final pdf = pw.Document(
      title: report.title.isEmpty ? "Mati Report" : report.title,
      author: "AstroNexus Mati AI",
    );

    final titleStyle = pw.TextStyle(
      fontSize: 24,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.indigo900,
    );
    final subtitleStyle = pw.TextStyle(
      fontSize: 11,
      color: PdfColors.blueGrey600,
    );
    final sectionTitleStyle = pw.TextStyle(
      fontSize: 15,
      fontWeight: pw.FontWeight.bold,
      color: PdfColors.indigo800,
    );
    const bodyStyle = pw.TextStyle(
      fontSize: 11.5,
      color: PdfColors.black,
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            "Generated by AstroNexus Mati AI",
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ),
        build: (context) {
          final widgets = <pw.Widget>[
            pw.Text(report.title.isEmpty ? "Mati Astrology Report" : report.title, style: titleStyle),
          ];

          if (report.subtitle.isNotEmpty) {
            widgets.add(pw.SizedBox(height: 4));
            widgets.add(pw.Text(report.subtitle, style: subtitleStyle));
          }

          if (report.generatedOn.isNotEmpty) {
            widgets.add(pw.SizedBox(height: 4));
            widgets.add(
              pw.Text("Generated on ${report.generatedOn}", style: subtitleStyle),
            );
          }

          widgets.add(pw.SizedBox(height: 14));
          widgets.add(
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: PdfColors.blue50,
                borderRadius: pw.BorderRadius.circular(12),
                border: pw.Border.all(color: PdfColors.blue100),
              ),
              child: pw.Text(
                report.summary.isEmpty ? response.answer : report.summary,
                style: bodyStyle,
              ),
            ),
          );

          if (response.timing != null && response.timing!.hasContent) {
            widgets.add(pw.SizedBox(height: 18));
            widgets.add(pw.Text("Timing Snapshot", style: sectionTitleStyle));
            widgets.add(pw.SizedBox(height: 8));

            if (response.timing!.favorableDates.isNotEmpty) {
              widgets.add(
                pw.Text(
                  "• Favorable dates: ${response.timing!.favorableDates.map((item) => item.date).join(", ")}",
                  style: bodyStyle,
                ),
              );
            }

            if (response.timing!.avoidDates.isNotEmpty) {
              widgets.add(
                pw.Text(
                  "• Use extra caution on: ${response.timing!.avoidDates.map((item) => item.date).join(", ")}",
                  style: bodyStyle,
                ),
              );
            }

            if (response.timing!.note.isNotEmpty) {
              widgets.add(
                pw.Text("• ${response.timing!.note}", style: bodyStyle),
              );
            }
          }

          for (final section in report.sections) {
            if (section.heading.isEmpty || section.content.isEmpty) {
              continue;
            }

            widgets.add(pw.SizedBox(height: 18));
            widgets.add(pw.Text(section.heading, style: sectionTitleStyle));
            widgets.add(pw.SizedBox(height: 7));
            widgets.add(pw.Text(section.content, style: bodyStyle));
          }

          if (response.analysis != null) {
            widgets.add(pw.SizedBox(height: 18));
            widgets.add(pw.Text("Astro Score", style: sectionTitleStyle));
            widgets.add(pw.SizedBox(height: 7));
            widgets.add(
              pw.Text(
                "Decision score ${response.analysis!.decisionScore.toStringAsFixed(0)}%, positive ${response.analysis!.positivePercentage.toStringAsFixed(0)}%, negative ${response.analysis!.negativePercentage.toStringAsFixed(0)}%.",
                style: bodyStyle,
              ),
            );
          }

          return widgets;
        },
      ),
    );

    final directory = await getApplicationDocumentsDirectory();
    final safeName = report.fileName.trim().isEmpty
        ? "mati_report.pdf"
        : report.fileName.trim();
    final file = File("${directory.path}/$safeName");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static Future<void> generateAndOpen(MatiChatResponse response) async {
    final file = await generatePdf(response);
    await OpenFilex.open(file.path);
  }
}
