// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHWw7WABUoCXSIeG1j71ar-MlaXavbx4',
    appId: '1:241031523033:web:356097f6186822cc3a6cc8',
    messagingSenderId: '241031523033',
    projectId: 'astronexus-3bee6',
    authDomain: 'astronexus-3bee6.firebaseapp.com',
    storageBucket: 'astronexus-3bee6.firebasestorage.app',
    measurementId: 'G-2TTDXWJM08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfds7c8DGygaDcKtHF4zE4RM9OWjb6SKc',
    appId: '1:241031523033:android:43e9cce1e4563b8d3a6cc8',
    messagingSenderId: '241031523033',
    projectId: 'astronexus-3bee6',
    storageBucket: 'astronexus-3bee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC1bEWE9ABkWoelRj5eaTfV-zyLcA7E58',
    appId: '1:241031523033:ios:129e4cdf13cd691e3a6cc8',
    messagingSenderId: '241031523033',
    projectId: 'astronexus-3bee6',
    storageBucket: 'astronexus-3bee6.firebasestorage.app',
    iosBundleId: 'com.example.astroTale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC1bEWE9ABkWoelRj5eaTfV-zyLcA7E58',
    appId: '1:241031523033:ios:129e4cdf13cd691e3a6cc8',
    messagingSenderId: '241031523033',
    projectId: 'astronexus-3bee6',
    storageBucket: 'astronexus-3bee6.firebasestorage.app',
    iosBundleId: 'com.example.astroTale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxHWw7WABUoCXSIeG1j71ar-MlaXavbx4',
    appId: '1:241031523033:web:8e395c637b73a8eb3a6cc8',
    messagingSenderId: '241031523033',
    projectId: 'astronexus-3bee6',
    authDomain: 'astronexus-3bee6.firebaseapp.com',
    storageBucket: 'astronexus-3bee6.firebasestorage.app',
    measurementId: 'G-ZDGNNVBWYC',
  );
}
